# Google App Engine configuration
runtime: python311

env_variables:
  STREAMLIT_SERVER_PORT: 8080
  STREAMLIT_SERVER_ADDRESS: 0.0.0.0

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 4

handlers:
- url: /.*
  script: auto